theme: jekyll-theme-minimal

title: Tanit
description: Diosa Cartaginesa venerada por muchos pueblos ribereños del Mediterráneo, como la propia ciudad de Cartago e Ibiza.
  
logo: "/assets/images/tanit.gif"

author:
  name: Fátima Garay
  email: fathygaray13@gmail.com
  
